# This file was generated by GoReleaser. DO NOT EDIT.
cask "gopen" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gopen"]
    end
  end

  version "1.5.5"

  on_macos do
    on_arm do
      sha256 "b2ac69ac8f49c1e4660ff5795894128f3fed880a4f5086c4d75945df5d3dcf9d"
      url "https://github.com/PixiBixi/gopen/releases/download/v#{version}/gopen_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0933dc564bfc9c07b0eabbb24f132e46190ec946b10ef83952b4d8b2e2fcefa5"
      url "https://github.com/PixiBixi/gopen/releases/download/v#{version}/gopen_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1d2e8bdecdc77cb291249403c08721437b4f037517bf9fba7543f5ca236b8c12"
      url "https://github.com/PixiBixi/gopen/releases/download/v#{version}/gopen_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "81b9a8ab45124c994cf87b0f1def776ef315e483c44fc5ab54a7e29c51a09dc3"
      url "https://github.com/PixiBixi/gopen/releases/download/v#{version}/gopen_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "gopen"
  desc "Open your git repository in the browser at the current branch and directory"
  homepage "https://github.com/PixiBixi/gopen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gopen"

  # No zap stanza required
end
