# This file was generated by GoReleaser. DO NOT EDIT.
cask "gopen" do
  version "1.5.1"

  on_macos do
    on_intel do
      sha256 "2f645615f3ec4381868ea5aac2ae7c4aebcf8dec7a4df1b76a06c956edd9e7f4"
      url "https://github.com/PixiBixi/gopen/releases/download/v#{version}/gopen_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/PixiBixi/gopen/"
    end
    on_arm do
      sha256 "da5011b9452430b134d650f9c6877e29b462d1b7e0ceee50a93f4705fa4b9899"
      url "https://github.com/PixiBixi/gopen/releases/download/v#{version}/gopen_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/PixiBixi/gopen/"
    end
  end

  on_linux do
    on_intel do
      sha256 "50602f03e787ceba0624efcc7fc3d8ab53d0725a29303a261b150cfea78c8d8f"
      url "https://github.com/PixiBixi/gopen/releases/download/v#{version}/gopen_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/PixiBixi/gopen/"
    end
    on_arm do
      sha256 "481ce0897caf1cdce364f684b2462795a11d3ef0ddf2a09a03c59127848301e1"
      url "https://github.com/PixiBixi/gopen/releases/download/v#{version}/gopen_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/PixiBixi/gopen/"
    end
  end

  name "gopen"
  desc "Open your git repository in the browser at the current branch and directory"
  homepage "https://github.com/PixiBixi/gopen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gopen"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gopen"]
    end
  end

  # No zap stanza required

end
