# This file was generated by GoReleaser. DO NOT EDIT.
cask "gopen" do
  version "1.5.4"

  on_macos do
    on_arm do
      sha256 "c66a6cc88eeee9077ed30cccde2f503f5498baad05bf8a4d0716ec118f2a290f"
      url "https://github.com/PixiBixi/gopen/releases/download/v#{version}/gopen_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "add0ff31291e5280fc9c500f5f661ded15e044de9f66fc8594458a4a1f71760e"
      url "https://github.com/PixiBixi/gopen/releases/download/v#{version}/gopen_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a32af177ad96bb3ef131fa8eba8fb61cf3ff48cf16d804a663d6986a2f81a419"
      url "https://github.com/PixiBixi/gopen/releases/download/v#{version}/gopen_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c1d15503a6ad1c27f97100bf3db4935bde97f04e59262c1e221053ee0d77fc57"
      url "https://github.com/PixiBixi/gopen/releases/download/v#{version}/gopen_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "gopen"
  desc "Open your git repository in the browser at the current branch and directory"
  homepage "https://github.com/PixiBixi/gopen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gopen"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gopen"]
    end
  end

  # No zap stanza required
end
