# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopen < Formula
  desc "Open your git repository in the browser at the current branch and directory"
  homepage "https://github.com/PixiBixi/gopen"
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PixiBixi/gopen/releases/download/v1.3.3/gopen_1.3.3_Darwin_x86_64.tar.gz"
      sha256 "ce9de3acefe8bd9898aa0938238ee3fec1e176a50093d49622e78d12dda4b089"

      define_method(:install) do
        bin.install "gopen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PixiBixi/gopen/releases/download/v1.3.3/gopen_1.3.3_Darwin_arm64.tar.gz"
      sha256 "0cc511bff72e334ec4a6deb6314623a9969a7e26320c322e3ce915784b55852b"

      define_method(:install) do
        bin.install "gopen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PixiBixi/gopen/releases/download/v1.3.3/gopen_1.3.3_Linux_x86_64.tar.gz"
      sha256 "f30ee5bade29d50cb7525f4f6c9daa3028321f55a97795939b228626ef7e359a"
      define_method(:install) do
        bin.install "gopen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PixiBixi/gopen/releases/download/v1.3.3/gopen_1.3.3_Linux_arm64.tar.gz"
      sha256 "929a72568a45d19266645be99883e49e5379d8cd50f5d7ee1bd118d4f9af7cca"
      define_method(:install) do
        bin.install "gopen"
      end
    end
  end
end
