# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopen < Formula
  desc "Open your git repository in the browser at the current branch and directory"
  homepage "https://github.com/PixiBixi/gopen"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PixiBixi/gopen/releases/download/v1.0.1/gopen_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "98cf446f967ae5eb4284bbf1b2d55e278e6bb865e577f2738841d8d959c82e22"

      def install
        bin.install "gopen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PixiBixi/gopen/releases/download/v1.0.1/gopen_1.0.1_Darwin_arm64.tar.gz"
      sha256 "5ee79b3dd9dc836447290013b4c9d1d13ee7ac1bfc14b40cb26cc66cbb494573"

      def install
        bin.install "gopen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PixiBixi/gopen/releases/download/v1.0.1/gopen_1.0.1_Linux_x86_64.tar.gz"
      sha256 "98e0f6b5585afeda2533a496444cd2f6ef139dc12e5eeea5136f5f23a12f34fb"
      def install
        bin.install "gopen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PixiBixi/gopen/releases/download/v1.0.1/gopen_1.0.1_Linux_arm64.tar.gz"
      sha256 "db6a486d81315ae0266b73138bb089327045e1192262f22bfbcab1f4f4e6ee29"
      def install
        bin.install "gopen"
      end
    end
  end
end
